

</p><div class="printfooter"></div>

        
        <!-- END content -->

        <div class="visualClear"></div>

      </div>

    </div>

  </div>
  <div id="column-one">

  <!-- BEGIN search -->

  <div id="p-search" class="portlet">

    <h5>

      <label for="searchInput">

      Search
      </label>

    </h5>

    <div class="pBody">

      <form name="searchform" action="http://www.estar.org.uk/wiki/index.php/Special:Search" id="searchform">

        <input id="searchInput" name="search" type="text" accesskey="f" value="" />

        <br />

        <input type='submit' name="go" class="searchButton" id="searchGoButton" value="Go" />

        <input type='submit' name="fulltext" class="searchButton" value="Search" />

      </form>

    </div>

  </div>

  <!-- END search -->
  <!-- BEGIN navigation -->

  <div class="portlet" id="p-nav">

    <h5>

      Navigation
    </h5>

    <div class="pBody">

        <ul><li> <a href="http://www.estar.org.uk/wiki/index.php/Main_Page" title="Main Page"> Main Page </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Project_News" title="Project News"> Project News </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Recent_Talks" title="Recent Talks"> Recent Talks </a>
</li><li> <a href="http://vo.astro.ex.ac.uk/estar/cgi-bin/status.cgi" class='external text' title="Network Status" rel="nofollow">Network Status </a>
<ul><li> <a href="http://vo.astro.ex.ac.uk/robonet-1.0/cgi-bin/status.cgi">Robonet-1.0</a>
</li><li> <b>UKIRT</b></li></ul>
</li>
<li> <a href="http://www.estar.org.uk/wiki/index.php/Current_Work" title="Current Work"> Current Work </a>
<ul><li> <a href="http://www.estar.org.uk/wiki/index.php/Deployment" title="Deployment"> Deployment </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Interoperability" title="Interoperability"> Interoperability </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/VOEvent" title="VOEvent"> VOEvent </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Plastic" title="Plastic"> Plastic </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Optimal_Sampling" title="Optimal Sampling">ADP </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Grid_Markets" title="Grid Markets"> Grid Markets </a>
</li></ul>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Web_Services" title="Web Services"> Web Services </a>
<ul><li> <a href="http://www.estar.org.uk/wiki/index.php/Catalogues" title="Catalogues"> Catalogues </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Events" title="Events"> Events </a>
</li></ul>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Standards_Work" title="Standards Work"> Standards Work </a>
<ul><li> <a href="http://www.estar.org.uk/wiki/index.php/HTN" title="HTN"> HTN </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/IVOA" title="IVOA"> IVOA </a>
</li></ul>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Prototyping" title="Prototyping"> Prototyping </a>
<ul><li> <a href="http://www.estar.org.uk/wiki/index.php/Current_Software" title="Current Software"> Current Software </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Previous_Work" title="Previous Work"> Previous Work </a>
</li></ul>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Publications" title="Publications"> Publications </a>
<ul><li> <a href="http://www.estar.org.uk/wiki/index.php/Papers" title="Papers"> Papers </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Standards_Work" title="Standards Work">Standards </a>
</li></ul>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Downloads" title="Downloads"> Downloads </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Media_Centre" title="Media Centre"> Media Centre </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Mailing_Lists" title="Mailing Lists"> Mailing Lists </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/EStar:About" title="EStar:About">About eSTAR </a>
<ul><li> <a href="http://www.estar.org.uk/wiki/index.php/The_Team" title="The Team"> The Team </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/EStar:About#The_Project" title="EStar:About">The Project </a>
</li></ul>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Special:Userlogin" title="Special:Userlogin"> User Login </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/Special:Recentchanges" title="Special:Recentchanges"> Recent Changes </a>
</li><li> <a href="http://www.estar.org.uk/wiki/index.php/EStar:Help" title="EStar:Help"> Help </a>
</li></ul>

    </div>

  </div>

  <!-- END navigation -->

 

<!-- Start of StatCounter Code -->
<script type="text/javascript" language="javascript">
var sc_project=1411996; 
var sc_invisible=1; 
var sc_partition=11; 
var sc_security="9dde236c"; 
</script>

<script type="text/javascript" language="javascript" src="http://www.statcounter.com/counter/counter.js"></script><noscript><a href="http://www.statcounter.com/" target="_blank"><img  src="http://c12.statcounter.com/counter.php?sc_project=1411996&amp;java=0&amp;security=9dde236c&amp;invisible=1" alt="php hit counter" border="0"></a> </noscript>
<!-- End of StatCounter Code -->

</div>


<!-- end of the left (by default at least) column -->

<div class="visualClear"></div>

<div id="footer">

  <ul id="f-list">

   
    
    <li id="f-lastmod">

       This page was automatically generated at LAST_MODIFIED_DATE
    </li>
 
    
    <li id="f-about">

      <a href="http://www.estar.org.uk/wiki/index.php/EStar:About" title="EStar:About">About EStar</a>
    </li>

    
    
    <li id="f-disclaimer">

      <a href="http://www.estar.org.uk/wiki/index.php/EStar:General_disclaimer" title="EStar:General disclaimer">Disclaimers</a>
    </li>

    <li id="f-developedby">

      (by <a href="http://www.dailyack.com/">Alasdair Allan</a>)

    </li>

    
  </ul>

</div>

</div>


</body></html>
