<font size='-2'><table border='0' width='95%'><tr>
<th align='left'>Message ID</th><th align='left'>Time</th><th align='left'>R.A.</th><th align='left'>Dec.</th><th align='left'>Star No.</th><th align='left'>Field</th></tr><tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-490.xml'>OGLE-2006-BLG-490</a></font></td><td><font color='grey'>2006-08-24T12:13:47</font></td><td><font color='grey'>271.077</font></td><td><font color='grey'>-27.120</font></td><td><font color='grey'>176603</font></td><td><font color='grey'>BLG234.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-489.xml'>OGLE-2006-BLG-489</a></font></td><td><font color='grey'>2006-08-24T12:13:47</font></td><td><font color='grey'>269.937</font></td><td><font color='grey'>-28.172</font></td><td><font color='grey'>192707</font></td><td><font color='grey'>BLG215.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-488.xml'>OGLE-2006-BLG-488</a></font></td><td><font color='grey'>2006-08-24T12:13:47</font></td><td><font color='grey'>267.411</font></td><td><font color='grey'>-30.371</font></td><td><font color='grey'>96621</font></td><td><font color='grey'>BLG179.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-487.xml'>OGLE-2006-BLG-487</a></font></td><td><font color='grey'>2006-08-24T12:13:47</font></td><td><font color='grey'>268.196</font></td><td><font color='grey'>-31.087</font></td><td><font color='grey'>1192</font></td><td><font color='grey'>BLG171.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-486.xml'>OGLE-2006-BLG-486</a></font></td><td><font color='grey'>2006-08-24T12:13:47</font></td><td><font color='grey'>268.800</font></td><td><font color='grey'>-29.271</font></td><td><font color='grey'>128446</font></td><td><font color='grey'>BLG102.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-485.xml'>OGLE-2006-BLG-485</a></font></td><td><font color='grey'>2006-08-23T19:06:57</font></td><td><font color='grey'>271.127</font></td><td><font color='grey'>-27.404</font></td><td><font color='grey'>143015</font></td><td><font color='grey'>BLG225.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-484.xml'>OGLE-2006-BLG-484</a></font></td><td><font color='grey'>2006-08-23T19:06:57</font></td><td><font color='grey'>268.857</font></td><td><font color='grey'>-29.651</font></td><td><font color='grey'>18497</font></td><td><font color='grey'>BLG102.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-483.xml'>OGLE-2006-BLG-483</a></font></td><td><font color='grey'>2006-08-23T19:06:57</font></td><td><font color='grey'>267.610</font></td><td><font color='grey'>-29.818</font></td><td><font color='grey'>15835</font></td><td><font color='grey'>BLG100.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-482.xml'>OGLE-2006-BLG-482</a></font></td><td><font color='grey'>2006-08-23T02:06:55</font></td><td><font color='grey'>267.796</font></td><td><font color='grey'>-30.515</font></td><td><font color='grey'>165169</font></td><td><font color='grey'>BLG179.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-481.xml'>OGLE-2006-BLG-481</a></font></td><td><font color='grey'>2006-08-23T02:06:55</font></td><td><font color='grey'>269.731</font></td><td><font color='grey'>-31.328</font></td><td><font color='grey'>64843</font></td><td><font color='grey'>BLG173.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-480.xml'>OGLE-2006-BLG-480</a></font></td><td><font color='grey'>2006-08-23T02:06:55</font></td><td><font color='grey'>268.902</font></td><td><font color='grey'>-30.378</font></td><td><font color='grey'>15443</font></td><td><font color='grey'>BLG103.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-479.xml'>OGLE-2006-BLG-479</a></font></td><td><font color='grey'>2006-08-21T10:09:20</font></td><td><font color='grey'>271.023</font></td><td><font color='grey'>-28.591</font></td><td><font color='grey'>4186</font></td><td><font color='grey'>BLG217.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-478.xml'>OGLE-2006-BLG-478</a></font></td><td><font color='grey'>2006-08-21T10:09:20</font></td><td><font color='grey'>269.814</font></td><td><font color='grey'>-28.167</font></td><td><font color='grey'>171348</font></td><td><font color='grey'>BLG215.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-477.xml'>OGLE-2006-BLG-477</a></font></td><td><font color='grey'>2006-08-21T10:09:20</font></td><td><font color='grey'>269.283</font></td><td><font color='grey'>-30.600</font></td><td><font color='grey'>61369</font></td><td><font color='grey'>BLG182.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-476.xml'>OGLE-2006-BLG-476</a></font></td><td><font color='grey'>2006-08-21T10:09:20</font></td><td><font color='grey'>268.116</font></td><td><font color='grey'>-32.295</font></td><td><font color='grey'>124871</font></td><td><font color='grey'>BLG155.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-475.xml'>OGLE-2006-BLG-475</a></font></td><td><font color='grey'>2006-08-20T14:29:03</font></td><td><font color='grey'>266.213</font></td><td><font color='grey'>-34.063</font></td><td><font color='grey'>124794</font></td><td><font color='grey'>BLG129.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-474.xml'>OGLE-2006-BLG-474</a></font></td><td><font color='grey'>2006-08-20T14:29:03</font></td><td><font color='grey'>269.286</font></td><td><font color='grey'>-28.402</font></td><td><font color='grey'>85702</font></td><td><font color='grey'>BLG214.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-473.xml'>OGLE-2006-BLG-473</a></font></td><td><font color='grey'>2006-08-20T14:29:03</font></td><td><font color='grey'>270.684</font></td><td><font color='grey'>-30.293</font></td><td><font color='grey'>75061</font></td><td><font color='grey'>BLG189.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-472.xml'>OGLE-2006-BLG-472</a></font></td><td><font color='grey'>2006-08-20T14:29:03</font></td><td><font color='grey'>267.891</font></td><td><font color='grey'>-30.889</font></td><td><font color='grey'>53170</font></td><td><font color='grey'>BLG180.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-471.xml'>OGLE-2006-BLG-471</a></font></td><td><font color='grey'>2006-08-20T14:29:03</font></td><td><font color='grey'>267.577</font></td><td><font color='grey'>-30.611</font></td><td><font color='grey'>53749</font></td><td><font color='grey'>BLG179.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-470.xml'>OGLE-2006-BLG-470</a></font></td><td><font color='grey'>2006-08-20T14:29:03</font></td><td><font color='grey'>269.132</font></td><td><font color='grey'>-31.886</font></td><td><font color='grey'>104543</font></td><td><font color='grey'>BLG164.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-469.xml'>OGLE-2006-BLG-469</a></font></td><td><font color='grey'>2006-08-18T15:21:13</font></td><td><font color='grey'>270.443</font></td><td><font color='grey'>-27.976</font></td><td><font color='grey'>46123</font></td><td><font color='grey'>BLG224.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-468.xml'>OGLE-2006-BLG-468</a></font></td><td><font color='grey'>2006-08-18T15:21:13</font></td><td><font color='grey'>269.577</font></td><td><font color='grey'>-30.180</font></td><td><font color='grey'>65143</font></td><td><font color='grey'>BLG188.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-467.xml'>OGLE-2006-BLG-467</a></font></td><td><font color='grey'>2006-08-17T17:28:45</font></td><td><font color='grey'>270.774</font></td><td><font color='grey'>-27.972</font></td><td><font color='grey'>40771</font></td><td><font color='grey'>BLG224.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-466.xml'>OGLE-2006-BLG-466</a></font></td><td><font color='grey'>2006-08-17T17:28:45</font></td><td><font color='grey'>271.309</font></td><td><font color='grey'>-30.756</font></td><td><font color='grey'>53197</font></td><td><font color='grey'>BLG185.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-465.xml'>OGLE-2006-BLG-465</a></font></td><td><font color='grey'>2006-08-16T16:57:06</font></td><td><font color='grey'>270.334</font></td><td><font color='grey'>-27.166</font></td><td><font color='grey'>75214</font></td><td><font color='grey'>BLG233.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-464.xml'>OGLE-2006-BLG-464</a></font></td><td><font color='grey'>2006-08-16T16:57:06</font></td><td><font color='grey'>270.104</font></td><td><font color='grey'>-27.454</font></td><td><font color='grey'>128034</font></td><td><font color='grey'>BLG223.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-463.xml'>OGLE-2006-BLG-463</a></font></td><td><font color='grey'>2006-08-16T16:57:06</font></td><td><font color='grey'>270.824</font></td><td><font color='grey'>-28.038</font></td><td><font color='grey'>137788</font></td><td><font color='grey'>BLG216.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-462.xml'>OGLE-2006-BLG-462</a></font></td><td><font color='grey'>2006-08-16T16:57:06</font></td><td><font color='grey'>270.812</font></td><td><font color='grey'>-28.471</font></td><td><font color='grey'>166370</font></td><td><font color='grey'>BLG216.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-461.xml'>OGLE-2006-BLG-461</a></font></td><td><font color='grey'>2006-08-16T16:57:06</font></td><td><font color='grey'>269.845</font></td><td><font color='grey'>-30.140</font></td><td><font color='grey'>113191</font></td><td><font color='grey'>BLG188.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-460.xml'>OGLE-2006-BLG-460</a></font></td><td><font color='grey'>2006-08-16T16:57:06</font></td><td><font color='grey'>268.698</font></td><td><font color='grey'>-29.932</font></td><td><font color='grey'>119102</font></td><td><font color='grey'>BLG101.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-459.xml'>OGLE-2006-BLG-459</a></font></td><td><font color='grey'>2006-08-14T14:24:56</font></td><td><font color='grey'>269.229</font></td><td><font color='grey'>-28.677</font></td><td><font color='grey'>69005</font></td><td><font color='grey'>BLG205.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-458.xml'>OGLE-2006-BLG-458</a></font></td><td><font color='grey'>2006-08-14T14:24:56</font></td><td><font color='grey'>268.597</font></td><td><font color='grey'>-29.501</font></td><td><font color='grey'>73178</font></td><td><font color='grey'>BLG195.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-457.xml'>OGLE-2006-BLG-457</a></font></td><td><font color='grey'>2006-08-14T14:24:56</font></td><td><font color='grey'>269.302</font></td><td><font color='grey'>-30.043</font></td><td><font color='grey'>72724</font></td><td><font color='grey'>BLG103.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-456.xml'>OGLE-2006-BLG-456</a></font></td><td><font color='grey'>2006-08-13T22:06:58</font></td><td><font color='grey'>270.118</font></td><td><font color='grey'>-28.044</font></td><td><font color='grey'>116550</font></td><td><font color='grey'>BLG215.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-455.xml'>OGLE-2006-BLG-455</a></font></td><td><font color='grey'>2006-08-13T22:06:58</font></td><td><font color='grey'>270.806</font></td><td><font color='grey'>-28.665</font></td><td><font color='grey'>80512</font></td><td><font color='grey'>BLG207.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-454.xml'>OGLE-2006-BLG-454</a></font></td><td><font color='grey'>2006-08-13T22:06:58</font></td><td><font color='grey'>268.525</font></td><td><font color='grey'>-30.622</font></td><td><font color='grey'>465</font></td><td><font color='grey'>BLG181.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-453.xml'>OGLE-2006-BLG-453</a></font></td><td><font color='grey'>2006-08-13T22:06:58</font></td><td><font color='grey'>269.363</font></td><td><font color='grey'>-30.276</font></td><td><font color='grey'>124566</font></td><td><font color='grey'>BLG103.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-452.xml'>OGLE-2006-BLG-452</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>269.969</font></td><td><font color='grey'>-29.025</font></td><td><font color='grey'>42785</font></td><td><font color='grey'>BLG206.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-451.xml'>OGLE-2006-BLG-451</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>269.871</font></td><td><font color='grey'>-28.622</font></td><td><font color='grey'>121973</font></td><td><font color='grey'>BLG206.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-450.xml'>OGLE-2006-BLG-450</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>268.002</font></td><td><font color='grey'>-31.127</font></td><td><font color='grey'>117863</font></td><td><font color='grey'>BLG171.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-449.xml'>OGLE-2006-BLG-449</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>268.048</font></td><td><font color='grey'>-31.191</font></td><td><font color='grey'>47533</font></td><td><font color='grey'>BLG171.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-448.xml'>OGLE-2006-BLG-448</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>268.748</font></td><td><font color='grey'>-30.304</font></td><td><font color='grey'>70731</font></td><td><font color='grey'>BLG103.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-447.xml'>OGLE-2006-BLG-447</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>269.399</font></td><td><font color='grey'>-29.822</font></td><td><font color='grey'>159997</font></td><td><font color='grey'>BLG103.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-446.xml'>OGLE-2006-BLG-446</a></font></td><td><font color='grey'>2006-08-12T11:33:23</font></td><td><font color='grey'>268.289</font></td><td><font color='grey'>-29.739</font></td><td><font color='grey'>163087</font></td><td><font color='grey'>BLG101.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-445.xml'>OGLE-2006-BLG-445</a></font></td><td><font color='grey'>2006-08-11T11:10:00</font></td><td><font color='grey'>269.102</font></td><td><font color='grey'>-28.774</font></td><td><font color='grey'>90472</font></td><td><font color='grey'>BLG205.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-444.xml'>OGLE-2006-BLG-444</a></font></td><td><font color='grey'>2006-08-11T11:10:00</font></td><td><font color='grey'>269.809</font></td><td><font color='grey'>-29.196</font></td><td><font color='grey'>148280</font></td><td><font color='grey'>BLG104.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-443.xml'>OGLE-2006-BLG-443</a></font></td><td><font color='grey'>2006-08-09T11:36:17</font></td><td><font color='grey'>269.489</font></td><td><font color='grey'>-32.424</font></td><td><font color='grey'>5288</font></td><td><font color='grey'>BLG157.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-442.xml'>OGLE-2006-BLG-442</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>270.019</font></td><td><font color='grey'>-27.714</font></td><td><font color='grey'>161282</font></td><td><font color='grey'>BLG223.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-441.xml'>OGLE-2006-BLG-441</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>272.161</font></td><td><font color='grey'>-27.993</font></td><td><font color='grey'>145683</font></td><td><font color='grey'>BLG218.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-440.xml'>OGLE-2006-BLG-440</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>270.611</font></td><td><font color='grey'>-28.839</font></td><td><font color='grey'>106491</font></td><td><font color='grey'>BLG207.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-439.xml'>OGLE-2006-BLG-439</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>268.588</font></td><td><font color='grey'>-29.443</font></td><td><font color='grey'>126641</font></td><td><font color='grey'>BLG195.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-438.xml'>OGLE-2006-BLG-438</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>270.497</font></td><td><font color='grey'>-29.903</font></td><td><font color='grey'>5607</font></td><td><font color='grey'>BLG189.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-437.xml'>OGLE-2006-BLG-437</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>269.449</font></td><td><font color='grey'>-29.846</font></td><td><font color='grey'>59971</font></td><td><font color='grey'>BLG188.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-436.xml'>OGLE-2006-BLG-436</a></font></td><td><font color='grey'>2006-08-04T12:52:33</font></td><td><font color='grey'>269.414</font></td><td><font color='grey'>-29.676</font></td><td><font color='grey'>222909</font></td><td><font color='grey'>BLG102.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-435.xml'>OGLE-2006-BLG-435</a></font></td><td><font color='grey'>2006-08-03T13:43:23</font></td><td><font color='grey'>270.339</font></td><td><font color='grey'>-30.324</font></td><td><font color='grey'>73758</font></td><td><font color='grey'>BLG189.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-434.xml'>OGLE-2006-BLG-434</a></font></td><td><font color='grey'>2006-08-03T13:43:23</font></td><td><font color='grey'>268.711</font></td><td><font color='grey'>-30.919</font></td><td><font color='grey'>88789</font></td><td><font color='grey'>BLG181.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-433.xml'>OGLE-2006-BLG-433</a></font></td><td><font color='grey'>2006-08-03T13:43:23</font></td><td><font color='grey'>268.673</font></td><td><font color='grey'>-30.081</font></td><td><font color='grey'>104024</font></td><td><font color='grey'>BLG101.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-432.xml'>OGLE-2006-BLG-432</a></font></td><td><font color='grey'>2006-07-30T14:55:23</font></td><td><font color='grey'>269.557</font></td><td><font color='grey'>-27.519</font></td><td><font color='grey'>5022</font></td><td><font color='grey'>BLG223.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-431.xml'>OGLE-2006-BLG-431</a></font></td><td><font color='grey'>2006-07-30T14:55:23</font></td><td><font color='grey'>269.486</font></td><td><font color='grey'>-27.999</font></td><td><font color='grey'>159578</font></td><td><font color='grey'>BLG214.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-430.xml'>OGLE-2006-BLG-430</a></font></td><td><font color='grey'>2006-07-30T14:55:23</font></td><td><font color='grey'>270.703</font></td><td><font color='grey'>-29.041</font></td><td><font color='grey'>161498</font></td><td><font color='grey'>BLG207.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-429.xml'>OGLE-2006-BLG-429</a></font></td><td><font color='grey'>2006-07-30T14:55:22</font></td><td><font color='grey'>268.121</font></td><td><font color='grey'>-29.927</font></td><td><font color='grey'>71611</font></td><td><font color='grey'>BLG101.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-428.xml'>OGLE-2006-BLG-428</a></font></td><td><font color='grey'>2006-07-28T13:01:37</font></td><td><font color='grey'>270.853</font></td><td><font color='grey'>-27.081</font></td><td><font color='grey'>17209</font></td><td><font color='grey'>BLG233.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-427.xml'>OGLE-2006-BLG-427</a></font></td><td><font color='grey'>2006-07-28T13:01:37</font></td><td><font color='grey'>270.566</font></td><td><font color='grey'>-28.771</font></td><td><font color='grey'>152286</font></td><td><font color='grey'>BLG207.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-426.xml'>OGLE-2006-BLG-426</a></font></td><td><font color='grey'>2006-07-28T13:01:37</font></td><td><font color='grey'>271.228</font></td><td><font color='grey'>-30.475</font></td><td><font color='grey'>9748</font></td><td><font color='grey'>BLG185.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-425.xml'>OGLE-2006-BLG-425</a></font></td><td><font color='grey'>2006-07-25T16:35:48</font></td><td><font color='grey'>267.261</font></td><td><font color='grey'>-33.399</font></td><td><font color='grey'>55282</font></td><td><font color='grey'>BLG139.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-424.xml'>OGLE-2006-BLG-424</a></font></td><td><font color='grey'>2006-07-22T20:05:32</font></td><td><font color='grey'>265.692</font></td><td><font color='grey'>-34.175</font></td><td><font color='grey'>11327</font></td><td><font color='grey'>BLG129.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-423.xml'>OGLE-2006-BLG-423</a></font></td><td><font color='grey'>2006-07-22T20:05:31</font></td><td><font color='grey'>268.651</font></td><td><font color='grey'>-29.556</font></td><td><font color='grey'>246217</font></td><td><font color='grey'>BLG101.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-422.xml'>OGLE-2006-BLG-422</a></font></td><td><font color='grey'>2006-07-21T10:05:55</font></td><td><font color='grey'>270.527</font></td><td><font color='grey'>-27.768</font></td><td><font color='grey'>101940</font></td><td><font color='grey'>BLG224.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-421.xml'>OGLE-2006-BLG-421</a></font></td><td><font color='grey'>2006-07-21T10:05:55</font></td><td><font color='grey'>270.721</font></td><td><font color='grey'>-28.976</font></td><td><font color='grey'>62792</font></td><td><font color='grey'>BLG207.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-420.xml'>OGLE-2006-BLG-420</a></font></td><td><font color='grey'>2006-07-21T10:05:55</font></td><td><font color='grey'>269.440</font></td><td><font color='grey'>-28.650</font></td><td><font color='grey'>94264</font></td><td><font color='grey'>BLG205.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-419.xml'>OGLE-2006-BLG-419</a></font></td><td><font color='grey'>2006-07-21T10:05:55</font></td><td><font color='grey'>270.205</font></td><td><font color='grey'>-29.817</font></td><td><font color='grey'>112077</font></td><td><font color='grey'>BLG189.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-418.xml'>OGLE-2006-BLG-418</a></font></td><td><font color='grey'>2006-07-21T10:05:55</font></td><td><font color='grey'>269.922</font></td><td><font color='grey'>-30.446</font></td><td><font color='grey'>59389</font></td><td><font color='grey'>BLG183.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-417.xml'>OGLE-2006-BLG-417</a></font></td><td><font color='grey'>2006-07-20T00:04:06</font></td><td><font color='grey'>268.005</font></td><td><font color='grey'>-30.384</font></td><td><font color='grey'>158497</font></td><td><font color='grey'>BLG180.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-416.xml'>OGLE-2006-BLG-416</a></font></td><td><font color='grey'>2006-07-18T22:11:25</font></td><td><font color='grey'>272.569</font></td><td><font color='grey'>-27.954</font></td><td><font color='grey'>54953</font></td><td><font color='grey'>BLG227.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-415.xml'>OGLE-2006-BLG-415</a></font></td><td><font color='grey'>2006-07-18T22:11:25</font></td><td><font color='grey'>270.197</font></td><td><font color='grey'>-27.996</font></td><td><font color='grey'>186227</font></td><td><font color='grey'>BLG215.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-414.xml'>OGLE-2006-BLG-414</a></font></td><td><font color='grey'>2006-07-18T22:11:25</font></td><td><font color='grey'>270.187</font></td><td><font color='grey'>-29.829</font></td><td><font color='grey'>103644</font></td><td><font color='grey'>BLG189.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-413.xml'>OGLE-2006-BLG-413</a></font></td><td><font color='grey'>2006-07-18T22:11:25</font></td><td><font color='grey'>269.327</font></td><td><font color='grey'>-30.010</font></td><td><font color='grey'>118143</font></td><td><font color='grey'>BLG103.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-408.xml'>OGLE-2006-BLG-408</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>272.067</font></td><td><font color='grey'>-26.760</font></td><td><font color='grey'>80470</font></td><td><font color='grey'>BLG242.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-407.xml'>OGLE-2006-BLG-407</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>271.187</font></td><td><font color='grey'>-26.452</font></td><td><font color='grey'>42272</font></td><td><font color='grey'>BLG241.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-406.xml'>OGLE-2006-BLG-406</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>269.900</font></td><td><font color='grey'>-27.120</font></td><td><font color='grey'>122044</font></td><td><font color='grey'>BLG232.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-405.xml'>OGLE-2006-BLG-405</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>271.835</font></td><td><font color='grey'>-27.514</font></td><td><font color='grey'>8559</font></td><td><font color='grey'>BLG226.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-404.xml'>OGLE-2006-BLG-404</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>271.131</font></td><td><font color='grey'>-27.589</font></td><td><font color='grey'>86475</font></td><td><font color='grey'>BLG225.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-403.xml'>OGLE-2006-BLG-403</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>269.907</font></td><td><font color='grey'>-29.794</font></td><td><font color='grey'>184558</font></td><td><font color='grey'>BLG188.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-402.xml'>OGLE-2006-BLG-402</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>269.737</font></td><td><font color='grey'>-31.465</font></td><td><font color='grey'>107888</font></td><td><font color='grey'>BLG173.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-401.xml'>OGLE-2006-BLG-401</a></font></td><td><font color='grey'>2006-07-16T23:06:59</font></td><td><font color='grey'>269.163</font></td><td><font color='grey'>-30.957</font></td><td><font color='grey'>176638</font></td><td><font color='grey'>BLG172.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-400.xml'>OGLE-2006-BLG-400</a></font></td><td><font color='grey'>2006-07-15T21:42:17</font></td><td><font color='grey'>270.358</font></td><td><font color='grey'>-28.557</font></td><td><font color='grey'>2238</font></td><td><font color='grey'>BLG216.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-399.xml'>OGLE-2006-BLG-399</a></font></td><td><font color='grey'>2006-07-15T21:42:17</font></td><td><font color='grey'>270.544</font></td><td><font color='grey'>-28.349</font></td><td><font color='grey'>140289</font></td><td><font color='grey'>BLG216.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-398.xml'>OGLE-2006-BLG-398</a></font></td><td><font color='grey'>2006-07-15T21:42:17</font></td><td><font color='grey'>271.051</font></td><td><font color='grey'>-28.794</font></td><td><font color='grey'>114203</font></td><td><font color='grey'>BLG208.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-397.xml'>OGLE-2006-BLG-397</a></font></td><td><font color='grey'>2006-07-15T21:42:17</font></td><td><font color='grey'>267.157</font></td><td><font color='grey'>-30.632</font></td><td><font color='grey'>976</font></td><td><font color='grey'>BLG179.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-396.xml'>OGLE-2006-BLG-396</a></font></td><td><font color='grey'>2006-07-15T21:42:17</font></td><td><font color='grey'>268.021</font></td><td><font color='grey'>-32.091</font></td><td><font color='grey'>49659</font></td><td><font color='grey'>BLG163.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-395.xml'>OGLE-2006-BLG-395</a></font></td><td><font color='grey'>2006-07-15T21:42:17</font></td><td><font color='grey'>266.738</font></td><td><font color='grey'>-33.542</font></td><td><font color='grey'>41461</font></td><td><font color='grey'>BLG139.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-394.xml'>OGLE-2006-BLG-394</a></font></td><td><font color='grey'>2006-07-15T21:42:16</font></td><td><font color='grey'>269.279</font></td><td><font color='grey'>-30.113</font></td><td><font color='grey'>132865</font></td><td><font color='grey'>BLG103.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-393.xml'>OGLE-2006-BLG-393</a></font></td><td><font color='grey'>2006-07-06T22:18:50</font></td><td><font color='grey'>270.968</font></td><td><font color='grey'>-27.900</font></td><td><font color='grey'>97693</font></td><td><font color='grey'>BLG225.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-392.xml'>OGLE-2006-BLG-392</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>270.003</font></td><td><font color='grey'>-27.446</font></td><td><font color='grey'>115486</font></td><td><font color='grey'>BLG223.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-391.xml'>OGLE-2006-BLG-391</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>269.157</font></td><td><font color='grey'>-30.839</font></td><td><font color='grey'>158139</font></td><td><font color='grey'>BLG182.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-390.xml'>OGLE-2006-BLG-390</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>269.072</font></td><td><font color='grey'>-31.437</font></td><td><font color='grey'>104462</font></td><td><font color='grey'>BLG172.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-389.xml'>OGLE-2006-BLG-389</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>271.167</font></td><td><font color='grey'>-28.093</font></td><td><font color='grey'>68460</font></td><td><font color='grey'>BLG217.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-388.xml'>OGLE-2006-BLG-388</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>269.597</font></td><td><font color='grey'>-28.011</font></td><td><font color='grey'>174286</font></td><td><font color='grey'>BLG214.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-387.xml'>OGLE-2006-BLG-387</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>271.057</font></td><td><font color='grey'>-29.548</font></td><td><font color='grey'>92576</font></td><td><font color='grey'>BLG196.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-386.xml'>OGLE-2006-BLG-386</a></font></td><td><font color='grey'>2006-07-06T22:18:49</font></td><td><font color='grey'>269.157</font></td><td><font color='grey'>-30.839</font></td><td><font color='grey'>234679</font></td><td><font color='grey'>BLG181.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-385.xml'>OGLE-2006-BLG-385</a></font></td><td><font color='grey'>2006-07-03T21:06:11</font></td><td><font color='grey'>272.409</font></td><td><font color='grey'>-27.576</font></td><td><font color='grey'>160088</font></td><td><font color='grey'>BLG227.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-384.xml'>OGLE-2006-BLG-384</a></font></td><td><font color='grey'>2006-07-02T20:43:47</font></td><td><font color='grey'>270.466</font></td><td><font color='grey'>-28.193</font></td><td><font color='grey'>122919</font></td><td><font color='grey'>BLG216.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-383.xml'>OGLE-2006-BLG-383</a></font></td><td><font color='grey'>2006-07-01T20:16:24</font></td><td><font color='grey'>270.073</font></td><td><font color='grey'>-30.478</font></td><td><font color='grey'>35376</font></td><td><font color='grey'>BLG183.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-382.xml'>OGLE-2006-BLG-382</a></font></td><td><font color='grey'>2006-07-01T20:16:24</font></td><td><font color='grey'>270.091</font></td><td><font color='grey'>-29.705</font></td><td><font color='grey'>45715</font></td><td><font color='grey'>BLG105.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-381.xml'>OGLE-2006-BLG-381</a></font></td><td><font color='grey'>2006-06-30T21:51:00</font></td><td><font color='grey'>270.331</font></td><td><font color='grey'>-27.865</font></td><td><font color='grey'>180393</font></td><td><font color='grey'>BLG224.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-375.xml'>OGLE-2006-BLG-375</a></font></td><td><font color='grey'>2006-07-11T19:12:00</font></td><td><font color='grey'>270.751</font></td><td><font color='grey'>-29.266</font></td><td><font color='grey'>82903</font></td><td><font color='grey'>BLG105.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-373.xml'>OGLE-2006-BLG-373</a></font></td><td><font color='grey'>2006-06-28T16:47:59</font></td><td><font color='grey'>268.786</font></td><td><font color='grey'>-29.545</font></td><td><font color='grey'>198691</font></td><td><font color='grey'>BLG102.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-372.xml'>OGLE-2006-BLG-372</a></font></td><td><font color='grey'>2006-06-28T00:00:00</font></td><td><font color='grey'>268.514</font></td><td><font color='grey'>-29.840</font></td><td><font color='grey'>224733</font></td><td><font color='grey'>BLG101.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-371.xml'>OGLE-2006-BLG-371</a></font></td><td><font color='grey'>2006-06-27T19:40:48</font></td><td><font color='grey'>271.416</font></td><td><font color='grey'>-26.484</font></td><td><font color='grey'>29197</font></td><td><font color='grey'>BLG241.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-370.xml'>OGLE-2006-BLG-370</a></font></td><td><font color='grey'>2006-07-14T14:38:23</font></td><td><font color='grey'>270.570</font></td><td><font color='grey'>-27.560</font></td><td><font color='grey'>160146</font></td><td><font color='grey'>BLG224.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-369.xml'>OGLE-2006-BLG-369</a></font></td><td><font color='grey'>2006-06-22T00:57:35</font></td><td><font color='grey'>270.561</font></td><td><font color='grey'>-27.653</font></td><td><font color='grey'>57886</font></td><td><font color='grey'>BLG224.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-368.xml'>OGLE-2006-BLG-368</a></font></td><td><font color='grey'>2006-07-12T21:36:00</font></td><td><font color='grey'>270.511</font></td><td><font color='grey'>-28.317</font></td><td><font color='grey'>188649</font></td><td><font color='grey'>BLG216.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-366.xml'>OGLE-2006-BLG-366</a></font></td><td><font color='grey'>2006-09-14T23:45:36</font></td><td><font color='grey'>269.623</font></td><td><font color='grey'>-29.515</font></td><td><font color='grey'>122579</font></td><td><font color='grey'>BLG104.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-365.xml'>OGLE-2006-BLG-365</a></font></td><td><font color='grey'>2006-07-16T12:57:35</font></td><td><font color='grey'>270.091</font></td><td><font color='grey'>-29.705</font></td><td><font color='grey'>83930</font></td><td><font color='grey'>BLG104.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-364.xml'>OGLE-2006-BLG-364</a></font></td><td><font color='grey'>2006-06-27T22:19:11</font></td><td><font color='grey'>268.470</font></td><td><font color='grey'>-29.596</font></td><td><font color='grey'>147762</font></td><td><font color='grey'>BLG101.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-363.xml'>OGLE-2006-BLG-363</a></font></td><td><font color='grey'>2006-07-14T17:45:36</font></td><td><font color='grey'>268.032</font></td><td><font color='grey'>-33.196</font></td><td><font color='grey'>155998</font></td><td><font color='grey'>BLG148.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-361.xml'>OGLE-2006-BLG-361</a></font></td><td><font color='grey'>2006-07-20T06:00:00</font></td><td><font color='grey'>267.948</font></td><td><font color='grey'>-30.797</font></td><td><font color='grey'>12871</font></td><td><font color='grey'>BLG180.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-360.xml'>OGLE-2006-BLG-360</a></font></td><td><font color='grey'>2006-06-26T02:24:00</font></td><td><font color='grey'>269.342</font></td><td><font color='grey'>-30.171</font></td><td><font color='grey'>100071</font></td><td><font color='grey'>BLG103.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-358.xml'>OGLE-2006-BLG-358</a></font></td><td><font color='grey'>2006-06-27T21:07:11</font></td><td><font color='grey'>268.277</font></td><td><font color='grey'>-30.474</font></td><td><font color='grey'>12595</font></td><td><font color='grey'>BLG180.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-357.xml'>OGLE-2006-BLG-357</a></font></td><td><font color='grey'>2006-06-24T16:19:11</font></td><td><font color='grey'>266.346</font></td><td><font color='grey'>-33.540</font></td><td><font color='grey'>31579</font></td><td><font color='grey'>BLG138.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-355.xml'>OGLE-2006-BLG-355</a></font></td><td><font color='grey'>2006-06-24T07:40:48</font></td><td><font color='grey'>271.019</font></td><td><font color='grey'>-27.183</font></td><td><font color='grey'>122363</font></td><td><font color='grey'>BLG234.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-354.xml'>OGLE-2006-BLG-354</a></font></td><td><font color='grey'>2007-02-15T05:45:36</font></td><td><font color='grey'>271.403</font></td><td><font color='grey'>-29.071</font></td><td><font color='grey'>147396</font></td><td><font color='grey'>BLG208.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-353.xml'>OGLE-2006-BLG-353</a></font></td><td><font color='grey'>2006-06-21T02:09:35</font></td><td><font color='grey'>268.057</font></td><td><font color='grey'>-33.062</font></td><td><font color='grey'>154774</font></td><td><font color='grey'>BLG148.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-352.xml'>OGLE-2006-BLG-352</a></font></td><td><font color='grey'>2006-07-13T11:02:24</font></td><td><font color='grey'>270.216</font></td><td><font color='grey'>-27.501</font></td><td><font color='grey'>58574</font></td><td><font color='grey'>BLG224.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-351.xml'>OGLE-2006-BLG-351</a></font></td><td><font color='grey'>2006-06-19T07:26:23</font></td><td><font color='grey'>269.914</font></td><td><font color='grey'>-27.937</font></td><td><font color='grey'>53620</font></td><td><font color='grey'>BLG223.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-350.xml'>OGLE-2006-BLG-350</a></font></td><td><font color='grey'>2006-06-24T12:43:12</font></td><td><font color='grey'>271.418</font></td><td><font color='grey'>-28.492</font></td><td><font color='grey'>106710</font></td><td><font color='grey'>BLG217.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-349.xml'>OGLE-2006-BLG-349</a></font></td><td><font color='grey'>2006-07-27T09:50:24</font></td><td><font color='grey'>270.543</font></td><td><font color='grey'>-28.044</font></td><td><font color='grey'>137187</font></td><td><font color='grey'>BLG216.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-348.xml'>OGLE-2006-BLG-348</a></font></td><td><font color='grey'>2006-06-26T19:40:48</font></td><td><font color='grey'>270.928</font></td><td><font color='grey'>-28.012</font></td><td><font color='grey'>209692</font></td><td><font color='grey'>BLG216.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-347.xml'>OGLE-2006-BLG-347</a></font></td><td><font color='grey'>2006-07-16T17:16:47</font></td><td><font color='grey'>270.879</font></td><td><font color='grey'>-28.245</font></td><td><font color='grey'>88484</font></td><td><font color='grey'>BLG216.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-346.xml'>OGLE-2006-BLG-346</a></font></td><td><font color='grey'>2006-06-27T11:02:24</font></td><td><font color='grey'>270.792</font></td><td><font color='grey'>-28.639</font></td><td><font color='grey'>134696</font></td><td><font color='grey'>BLG207.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-345.xml'>OGLE-2006-BLG-345</a></font></td><td><font color='grey'>2006-06-18T08:38:23</font></td><td><font color='grey'>272.532</font></td><td><font color='grey'>-29.431</font></td><td><font color='grey'>45976</font></td><td><font color='grey'>BLG198.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-344.xml'>OGLE-2006-BLG-344</a></font></td><td><font color='grey'>2006-06-18T17:31:12</font></td><td><font color='grey'>268.504</font></td><td><font color='grey'>-29.378</font></td><td><font color='grey'>15045</font></td><td><font color='grey'>BLG195.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-342.xml'>OGLE-2006-BLG-342</a></font></td><td><font color='grey'>2006-06-23T09:21:36</font></td><td><font color='grey'>269.440</font></td><td><font color='grey'>-30.379</font></td><td><font color='grey'>158524</font></td><td><font color='grey'>BLG182.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-341.xml'>OGLE-2006-BLG-341</a></font></td><td><font color='grey'>2006-06-28T00:00:00</font></td><td><font color='grey'>268.801</font></td><td><font color='grey'>-30.810</font></td><td><font color='grey'>206424</font></td><td><font color='grey'>BLG181.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-340.xml'>OGLE-2006-BLG-340</a></font></td><td><font color='grey'>2006-07-15T23:31:12</font></td><td><font color='grey'>269.450</font></td><td><font color='grey'>-31.163</font></td><td><font color='grey'>131844</font></td><td><font color='grey'>BLG173.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-339.xml'>OGLE-2006-BLG-339</a></font></td><td><font color='grey'>2006-06-19T12:28:47</font></td><td><font color='grey'>269.016</font></td><td><font color='grey'>-29.647</font></td><td><font color='grey'>47340</font></td><td><font color='grey'>BLG102.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-338.xml'>OGLE-2006-BLG-338</a></font></td><td><font color='grey'>2006-06-25T07:26:23</font></td><td><font color='grey'>269.526</font></td><td><font color='grey'>-27.754</font></td><td><font color='grey'>86488</font></td><td><font color='grey'>BLG223.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-337.xml'>OGLE-2006-BLG-337</a></font></td><td><font color='grey'>2006-07-30T04:47:59</font></td><td><font color='grey'>271.846</font></td><td><font color='grey'>-29.752</font></td><td><font color='grey'>5539</font></td><td><font color='grey'>BLG197.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-336.xml'>OGLE-2006-BLG-336</a></font></td><td><font color='grey'>2006-06-18T01:40:48</font></td><td><font color='grey'>267.782</font></td><td><font color='grey'>-29.528</font></td><td><font color='grey'>186</font></td><td><font color='grey'>BLG194.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-333.xml'>OGLE-2006-BLG-333</a></font></td><td><font color='grey'>2006-06-25T08:38:23</font></td><td><font color='grey'>271.095</font></td><td><font color='grey'>-27.595</font></td><td><font color='grey'>122145</font></td><td><font color='grey'>BLG225.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-332.xml'>OGLE-2006-BLG-332</a></font></td><td><font color='grey'>2006-06-23T05:16:47</font></td><td><font color='grey'>271.290</font></td><td><font color='grey'>-27.873</font></td><td><font color='grey'>143975</font></td><td><font color='grey'>BLG225.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-329.xml'>OGLE-2006-BLG-329</a></font></td><td><font color='grey'>2006-06-26T14:52:48</font></td><td><font color='grey'>270.514</font></td><td><font color='grey'>-29.638</font></td><td><font color='grey'>142793</font></td><td><font color='grey'>BLG105.1</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-328.xml'>OGLE-2006-BLG-328</a></font></td><td><font color='grey'>2006-06-29T14:09:35</font></td><td><font color='grey'>268.442</font></td><td><font color='grey'>-29.285</font></td><td><font color='grey'>94547</font></td><td><font color='grey'>BLG195.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-327.xml'>OGLE-2006-BLG-327</a></font></td><td><font color='grey'>2006-06-12T01:40:48</font></td><td><font color='grey'>270.597</font></td><td><font color='grey'>-30.430</font></td><td><font color='grey'>57208</font></td><td><font color='grey'>BLG184.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-326.xml'>OGLE-2006-BLG-326</a></font></td><td><font color='grey'>2006-06-16T18:57:35</font></td><td><font color='grey'>268.619</font></td><td><font color='grey'>-31.224</font></td><td><font color='grey'>13113</font></td><td><font color='grey'>BLG172.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-325.xml'>OGLE-2006-BLG-325</a></font></td><td><font color='grey'>2006-06-20T11:31:12</font></td><td><font color='grey'>270.394</font></td><td><font color='grey'>-29.185</font></td><td><font color='grey'>171875</font></td><td><font color='grey'>BLG105.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-324.xml'>OGLE-2006-BLG-324</a></font></td><td><font color='grey'>2006-06-20T14:52:48</font></td><td><font color='grey'>269.952</font></td><td><font color='grey'>-29.534</font></td><td><font color='grey'>106003</font></td><td><font color='grey'>BLG104.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-323.xml'>OGLE-2006-BLG-323</a></font></td><td><font color='grey'>2006-06-16T11:02:24</font></td><td><font color='grey'>270.190</font></td><td><font color='grey'>-28.679</font></td><td><font color='grey'>73777</font></td><td><font color='grey'>BLG206.4</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-320.xml'>OGLE-2006-BLG-320</a></font></td><td><font color='grey'>2006-06-18T07:40:48</font></td><td><font color='grey'>269.073</font></td><td><font color='grey'>-30.601</font></td><td><font color='grey'>83522</font></td><td><font color='grey'>BLG181.3</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-319.xml'>OGLE-2006-BLG-319</a></font></td><td><font color='grey'>2006-06-13T07:12:00</font></td><td><font color='grey'>268.814</font></td><td><font color='grey'>-31.331</font></td><td><font color='grey'>78398</font></td><td><font color='grey'>BLG172.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-318.xml'>OGLE-2006-BLG-318</a></font></td><td><font color='grey'>2006-06-11T12:14:23</font></td><td><font color='grey'>269.636</font></td><td><font color='grey'>-29.311</font></td><td><font color='grey'>29549</font></td><td><font color='grey'>BLG104.5</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-317.xml'>OGLE-2006-BLG-317</a></font></td><td><font color='grey'>2006-06-17T21:07:11</font></td><td><font color='grey'>269.330</font></td><td><font color='grey'>-29.645</font></td><td><font color='grey'>37568</font></td><td><font color='grey'>BLG102.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-315.xml'>OGLE-2006-BLG-315</a></font></td><td><font color='grey'>2006-06-11T07:40:48</font></td><td><font color='grey'>270.836</font></td><td><font color='grey'>-27.904</font></td><td><font color='grey'>85682</font></td><td><font color='grey'>BLG225.8</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-314.xml'>OGLE-2006-BLG-314</a></font></td><td><font color='grey'>2006-06-12T16:33:35</font></td><td><font color='grey'>270.890</font></td><td><font color='grey'>-30.698</font></td><td><font color='grey'>88573</font></td><td><font color='grey'>BLG184.2</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-312.xml'>OGLE-2006-BLG-312</a></font></td><td><font color='grey'>2006-06-11T19:26:24</font></td><td><font color='grey'>271.407</font></td><td><font color='grey'>-26.477</font></td><td><font color='grey'>28903</font></td><td><font color='grey'>BLG241.6</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-309.xml'>OGLE-2006-BLG-309</a></font></td><td><font color='grey'>2006-06-28T10:19:11</font></td><td><font color='grey'>270.194</font></td><td><font color='grey'>-27.725</font></td><td><font color='grey'>157271</font></td><td><font color='grey'>BLG224.7</font></td></tr>

<tr><td><font color='grey'><a href='http://www.estar.org.uk/voevent/eSTAR/uk.org.estar/pl.edu.ogle/OGLE-2006-BLG-307.xml'>OGLE-2006-BLG-307</a></font></td><td><font color='grey'>2006-06-11T02:38:23</font></td><td><font color='grey'>269.180</font></td><td><font color='grey'>-30.404</font></td><td><font color='grey'>8484</font></td><td><font color='grey'>BLG103.1</font></td></tr>

</table></font>