<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<meta name="KEYWORDS" content="Main Page,Deployment,HTN,IVOA,Media Centre,OGLE,VOEvent" />
<meta name="robots" content="index,follow" />
<link rel="shortcut icon" href="http://www.estar.org.uk/favicon.ico" />

<title>

VOEvent Manual Injection
</title>

<style type="text/css" media="screen,projection">

/*<![CDATA[*/ @import "http://www.estar.org.uk/wiki/skins/estar/main.css"; /*]]>*/

</style>


<script type="text/javascript" src="http://www.estar.org.uk/wiki/index.php?title=-&amp;action=raw&amp;smaxage=0&amp;gen=js"></script>


<script type="text/javascript" src="http://www.estar.org.uk/wiki/skins/common/wikibits.js"></script>

<script type="text/javascript" src="../js/validate.js"></script>
<link href="../css/validate.css" rel="stylesheet" type="text/css" />

<style type="text/css">

</style>




 
  <link rel="icon" href="http://www.estar.org.uk/favicon.ico" type="image/x-icon"> 
  <link rel="shortcut icon" href="http://www.estar.org.uk/favicon.ico" type="image/x-icon"> 
</head>

<body onload="setFocus()"
        class="ns-0">

<!-- BEGIN titleBar -->

<div id="titleBar"><a href="/"><img src="http://www.estar.org.uk/wiki/skins/estar/titlebar_logo.png" alt="The eSTAR Project" border="0" height="65" width="375" /></a></div>

<!-- END titleBar -->

<div id="globalWrapper">

  <div id="column-content">

    <div id="content"> <a name="top" id="contentTop"></a>

      
      <h1 class="firstHeading">

        VOEvent Manual Injection
      </h1>

      <h3 id="siteSub">

        From EStar
      </h3>

      <div id="bodyContent">

        <div id="contentSub">

          
        </div>


        
