#! /bin/tcsh

/work/estar/third_generation/bin/ogle_fetch_v2.pl -hours '4.0' -long '149.06166' -lat '31.27333' -elev '1149' -user kdh1 -pass EXOfollowup -project exoplanet >& ~estar/logs/ogle/ogle_FTS.`date -Iseconds` &

