#! /bin/tcsh

/work/estar/third_generation/bin/ogle_fetch_v2.pl -hours '2.0' -long '-156.24' -lat '20.70666' -elev '3054' -user kdh1 -pass EXOfollowup -project exoplanet >& ~estar/logs/ogle/ogle_FTN.`date -Iseconds` &

